import 'package:flutter/material.dart';

import 'backend_message_translator.dart';

class AppLocalizations {
  final Locale locale;

  AppLocalizations(this.locale);

  static AppLocalizations of(BuildContext context) {
    return Localizations.of<AppLocalizations>(context, AppLocalizations) ??
        AppLocalizations(const Locale('ar'));
  }

  static const LocalizationsDelegate<AppLocalizations> delegate =
      _AppLocalizationsDelegate();

  bool get isArabic => locale.languageCode == 'ar';

  static final Map<String, Map<String, String>> _localizedValues = {
    'ar': {
      // General & Actions
      'app_name': 'إدارة مزود خدمة الانترنت الفتح',
      'app_subtitle': 'المنظومة الإدارية المتكاملة لخدمات الإنترنت',
      'welcome_admin': 'مرحباً بك في لوحة تحكم شركة الفتح',
      'status_connected': 'متصل بالسيرفر',
      'status_connected_short': 'متصل',
      'theme_system': 'ثيم الجهاز (تلقائي)',
      'theme_dark': 'الوضع الليلي',
      'theme_light': 'الوضع النهاري',
      'lang_system': 'لغة الجهاز (تلقائي)',
      'lang_ar': 'العربية',
      'lang_en': 'English',
      'lang_switch': 'English',
      'confirm': 'تأكيد',
      'cancel': 'إلغاء',
      'close': 'إغلاق',
      'save': 'حفظ',
      'delete': 'حذف',
      'edit': 'تعديل',
      'search': 'بحث',
      'filter': 'فلترة',
      'refresh': 'تحديث',
      'back': 'رجوع',
      'logout': 'تسجيل الخروج',
      'or': 'أو',

      // Splash Screen
      'splash_loading': 'جاري تهيئة منظومة الفتح...',
      'splash_version': 'الإصدار 1.0.0 الموحد',
      'splash_step_resources': 'تحميل الموارد والخطوط...',
      'splash_step_network': 'فحص إعدادات الاتصال بالسيرفر...',
      'splash_step_system': 'تهيئة منظومة إدارة الفتح...',
      'splash_step_completed': 'اكتملت التهيئة بنجاح',

      // Services Hub
      'services_title': 'الخدمات الإدارية للمزود',
      'service_support': 'قسم الدعم الفني والمتابعات',
      'service_support_desc': 'متابعة اتصالات المشتركين، حل الأعطال، والمزامنة اللحظية مع Google Sheets',
      'service_support_loading': 'جاري إعداد التذاكر وجدول المتابعة...',
      'service_subscribers': 'إدارة المشتركين والخطوط',
      'service_subscribers_desc': 'سجلات الحسابات، الباقات، وتجديد الاشتراكات',
      'service_network': 'مراقبة الشبكة والمقاسم',
      'service_network_desc':
          'مراقبة استقرار الخدمة، جودة الخطوط، وأداء السيرفرات',
      'service_billing': 'الفواتير والحسابات المالية',
      'service_billing_desc':
          'إدارة المقبوضات الشهرية، الذمم، والتقارير المالية للمزود',
      'coming_soon': 'قيد التطوير',
      'active_now': 'نشط ومتاح',
      'enter_service': 'دخول القسم',

      // Technical Support & Tickets
      'status_resolved': 'تم الحل',
      'status_in_progress': 'قيد الحل',
      'status_unresolved': 'لم يتم الحل',
      'ticket_new': 'تسجيل تذكرة جديدة',
      'ticket_number': 'رقم التذكرة',
      'subscriber_name': 'اسم المشترك',
      'landline_number': 'الرقم الأرضي',
      'problem_type': 'نوع المشكلة',
      'solution_method': 'طريقة الحل',
      'description': 'التوصيف',
      'employee': 'الموظف',
      'date': 'التاريخ',
      'time': 'الوقت',
      'actions': 'الإجراءات',
      'no_data': 'لا توجد بيانات متاحة حالياً',

      // Form Validation
      'val_required': 'هذا الحقل مطلوب',
      'val_landline_empty': 'يرجى إدخال رقم الهاتف',
      'val_landline_digits': 'رقم الهاتف يجب أن يحتوي على أرقام فقط',
      'val_landline_length': 'رقم الهاتف يجب أن يتألف من 10 أرقام تماماً',
      'val_subscriber_empty': 'يرجى إدخال اسم المشترك',
      'val_subscriber_length': 'اسم المشترك قصير جداً (3 أحرف على الأقل)',
      'val_mobile_empty': 'يرجى إدخال رقم الهاتف المحمول',
      'val_mobile_invalid':
          'رقم الموبايل يجب أن يتألف من 10 أرقام (مثال: 09xxxxxxxx)',
      'val_username_empty': 'يرجى إدخال اسم المستخدم',
      'val_password_empty': 'يرجى إدخال كلمة المرور',
      'val_password_short': 'كلمة المرور قصيرة جداً (4 خانات على الأقل)',

      // Authentication & Login
      'login_title': 'تسجيل الدخول للمنظومة',
      'login_subtitle': 'أدخل بيانات حسابك للوصول إلى لوحة الإدارة والخدمات',
      'username': 'اسم المستخدم',
      'username_hint': 'مثال: admin أو hashem',
      'password': 'كلمة المرور',
      'password_hint': '••••••••',
      'remember_me': 'تذكرني على هذا الجهاز',
      'remember_me_tooltip': 'حفظ جلسة الدخول وتفعيل الوصول السريع بدون إنترنت',
      'sign_in': 'تسجيل الدخول',
      'signing_in': 'جاري التحقق والمصادقة...',
      'login_success': 'تم تسجيل الدخول بنجاح',
      'offline_mode_banner':
          'تم الدخول في وضع عدم الاتصال (بيانات مخزنة محلياً)',
      'forgot_password': 'نسيت كلمة المرور؟',
      'forgot_password_desc':
          'يرجى مراجعة إدارة منظومة الفتح لإعادة ضبط كلمة المرور',
      'show_password': 'إظهار كلمة المرور',
      'hide_password': 'إخفاء كلمة المرور',
      'need_help': 'تحتاج إلى مساعدة؟',
      'contact_admin': 'تواصل مع الدعم الفني والإدارة',
      'security_badge': 'اتصال آمن ومشفر 256-bit',
      'preview_skeleton': 'معاينة التحميل الهيكلي (Skeleton)',
      'login_brand_desc': 'بوابة التحكم الموحدة لخدمات تزويد الإنترنت، متابعات المشتركين، وجداول الدوام الذكية.',
      'feature_tickets_title': 'إدارة تذاكر الدعم الفني اللحظية',
      'feature_tickets_desc':
          'مزامنة مباشرة مع Google Sheets وتحديث حالات المشتركين',
      'feature_geofence_title': 'الدوام الذكي مع التحقق الجغرافي (Geofence)',
      'feature_geofence_desc': 'حضور وانصراف دقيق داخل نطاق مقر ومقاسم الشركة',
      'feature_rbac_title': 'أمان متقدم ومصفوفة صلاحيات (RBAC)',
      'feature_rbac_desc':
          'فصل مهام دقيق لجميع أقسام الشركة مع سجل تدقيق غير قابل للتعديل',
      'whatsapp_contact': 'تواصل مع الدعم الفني عبر واتساب',
      'whatsapp_launch_error': 'تعذر فتح تطبيق واتساب، يرجى المحاولة لاحقاً',
      'login_error_empty_fields': 'يرجى إدخال اسم المستخدم وكلمة المرور',
      'login_error_invalid_password': 'كلمة المرور غير صحيحة',
      'login_error_user_not_found': 'اسم المستخدم غير موجود',
      'login_error_account_disabled':
          'تم تعطيل هذا الحساب، يرجى مراجعة إدارة الفتح',
      'login_error_network':
          'تعذر الاتصال بالسيرفر، يرجى التحقق من اتصال الإنترنت',
      'login_error_generic':
          'فشل تسجيل الدخول، يرجى التحقق من اسم المستخدم وكلمة المرور',

      // Navigation & Sections
      'nav_home': 'الرئيسية',
      'nav_tickets': 'المتابعات الفنية',
      'nav_attendance': 'سجل الدوام',
      'nav_employees': 'الموظفون والصلاحيات',
      'nav_settings': 'الإعدادات والحساب',

      // Confirm Dialog
      'confirm_logout_title': 'تأكيد تسجيل الخروج',
      'confirm_logout_msg':
          'هل أنت متأكد من رغبتك في تسجيل الخروج من منظومة الفتح؟',
      'confirm_logout_message':
          'هل أنت متأكد من رغبتك في تسجيل الخروج من منظومة الفتح؟',
      'confirm_logout_button': 'تسجيل الخروج',
      'toggle_sidebar': 'تبديل القائمة الجانبية',

      // Dashboard & Statistics
      'stat_total_tickets': 'إجمالي التذاكر',
      'stat_in_progress': 'تذاكر قيد الحل',
      'stat_resolved_today': 'تم حلها اليوم',
      'stat_attendance_status': 'حالة دوام اليوم',
      'stat_present': 'حاضر بالعمل',
      'stat_not_checked_in': 'لم يسجل حضور',
      'stat_active_users': 'الموظفون النشطون',
      'stat_quick_actions': 'الإجراءات السريعة',
      'stat_recent_tickets': 'أحدث المتابعات المسجلة',
      'stat_view_all': 'عرض الكل',
      'stat_refresh_data': 'تحديث البيانات',
      'stat_offline_indicator': 'وضع محلي غير متصل بالشبكة',
      'action_new_ticket': 'تسجيل تذكرة',
      'action_check_in': 'تسجيل الحضور',
      'action_manage_users': 'إدارة الموظفين',
      'action_payroll_audit': 'تدقيق الرواتب',
      'action_settings': 'إعدادات الحساب',

      // Modules Placeholders
      'tickets_view_title': 'إدارة المتابعات الفنية والأعطال',
      'tickets_view_desc': 'متابعة اتصالات المشتركين، تسجيل الأعطال، وتحديث الحالات فورياً في جداول البيانات',
      'attendance_view_title': 'إدارة الحضور والانصراف والدوام',
      'attendance_view_desc': 'تسجيل الحضور عبر الـ GPS، التحقق من النطاق الجغرافي للمقر، ومراقبة الورديات والخصومات',
      'employees_view_title': 'إدارة الموظفين والحسابات والصلاحيات',
      'employees_view_desc': 'إدارة بيانات كادر العمل، مصفوفة الصلاحيات (RBAC)، واستعراض سجل التدقيق والرقابة',
      'settings_view_title': 'إعدادات التطبيق والحساب الشخصي',
      'settings_view_desc':
          'إدارة تفضيلات المظهر واللغة، الأمان، وتفاصيل الحساب وجلسة الدخول',

      // User Roles
      'role_admin': 'أدمن النظام',
      'role_gm': 'المدير العام',
      'role_finance': 'المحاسبة والمالية',
      'role_support_manager': 'مدير الدعم الفني',
      'role_sales_manager': 'مدير المبيعات',
      'role_support': 'فني الدعم الفني',
      'role_sales': 'موظف المبيعات',

      // Errors
      'error_network_connection': 'لا يوجد اتصال بالإنترنت، يرجى فحص الشبكة',
      'error_network_timeout': 'انتهت مهلة انتظار استجابة الخادم',
      'error_server_internal': 'حدث خطأ غير متوقع في الخادم',
      'error_unauthorized': 'غير مصرح، يرجى إعادة تسجيل الدخول',
      'error_forbidden': 'ليس لديك الصلاحيات الكافية لتنفيذ هذا الإجراء',
      'error_not_found': 'العنصر المطلوب غير موجود',
      'error_validation_failed': 'بيانات الإدخال غير صالحة',
      'error_cache_failure': 'فشل الوصول إلى الذاكرة المحلية المخزنة',
      'error_unknown': 'حدث خطأ غير متوقع',
      'auth_session_expired': 'انتهت صلاحية الجلسة المحلية، يرجى الاتصال بالإنترنت وتسجيل الدخول مجدداً',

      // Tickets Module
      'search_tickets_hint': 'بحث برقم الهاتف، اسم المشترك، نوع المشكلة...',
      'switch_to_cards': 'عرض بنمط البطاقات',
      'switch_to_table': 'عرض بنمط الجدول',
      'add_ticket_btn': 'إضافة تذكرة',
      'col_ticket_id': 'رقم التذكرة',
      'col_subscriber': 'المشترك',
      'col_landline': 'الهاتف الأرضي',
      'col_problem': 'نوع المشكلة',
      'col_status': 'الحالة',
      'col_employee': 'الموظف المسؤول',
      'col_date_time': 'التاريخ والوقت',
      'view_details': 'عرض التفاصيل',
      'edit_ticket': 'تعديل التذكرة',
      'all': 'كافة',
      'showing': 'المعروض',
      'clear_filters': 'مسح الفلاتر',
      'selected_items': 'العناصر المحددة',
      'clear_selection': 'إلغاء التحديد',
      'page': 'الصفحة',
      'unassigned': 'غير مسند',
      'badge_complaint': 'شكوى',
      'pending_sync': 'بانتظار المزامنة السحابية',
      'status_syncing': 'جاري المزامنة...',
      'status_offline_cache': 'بيانات محلية (أوفلاين)',
      'sync_now_tooltip': 'مزامنة فورية الآن',
      'no_tickets_found_title': 'لا توجد تذاكر مطابقة',
      'no_tickets_found_desc':
          'لم نتمكن من العثور على تذاكر مطابقة لمعايير البحث والفلترة',
      'dialog_add_ticket_title': 'تسجيل تذكرة متابعة جديدة',
      'dialog_add_ticket_desc': 'إدخال بيانات المشترك وتوصيف المشكلة الفنية',
      'subscriber_name_label': 'اسم المشترك',
      'subscriber_name_hint': 'أدخل اسم المشترك بالكامل',
      'val_subscriber_required': 'اسم المشترك مطلوب',
      'landline_label': 'رقم الهاتف الأرضي',
      'val_landline_required': 'رقم الهاتف الأرضي مطلوب',
      'mobile_label': 'رقم الموبايل',
      'problem_type_label': 'نوع المشكلة',
      'add_new_problem_type': 'إضافة مشكلة جديدة',
      'new_problem_name_hint': 'أدخل اسم المشكلة الجديدة...',
      'select_problem_required': 'يرجى اختيار أو إدخال نوع المشكلة',
      'assigned_to_label': 'الموظف المسند إليه',
      'priority_label': 'مستوى الأولوية',
      'is_complaint_ticket': 'تيكيت شكوى فنية (Complaint)',
      'is_complaint_ticket_desc':
          'تحديد كشكوى لتفعيل أولوية المتابعة الخاصة والتصعيد',
      'description_label': 'التوصيف وملاحظات الاتصال',
      'description_hint': 'أدخل تفاصيل المشكلة وتوجيهات المتابعة...',
      'save_ticket_btn': 'تسجيل وحفظ التذكرة',
      'tab_ticket_details': 'تفاصيل التذكرة وتحديث الحل',
      'tab_audit_trail': 'سجل التدقيق والتعديلات',
      'update_status_label': 'تحديث الحالة السريعة',
      'solution_method_label': 'طريقة الحل المنفذة',
      'solution_method_hint': 'اكتب الإجراء الذي تم لحل العطل...',
      'audit_notes_label': 'ملاحظات التدقيق وسبب التعديل',
      'audit_notes_hint': 'توثيق سبب التغيير بسجل الرقابة...',
      'save_changes': 'حفظ التعديلات',
      'no_audit_history': 'لا توجد تعديلات مسجلة بعد لهذه التذكرة',
      'ticket_add_success': 'تم تسجيل التذكرة بنجاح',
      'ticket_update_success': 'تم تحديث التذكرة بنجاح',
      'problem_add_success': 'تمت إضافة نوع المشكلة الجديد بنجاح',
      'sync_success': 'تمت مزامنة جميع العمليات المعلقة بنجاح',
      'close_all_tickets_btn': 'إغلاق كافة التذاكر',
      'tickets_bulk_close_title': 'تأكيد إغلاق كافة التذاكر المفتوحة',
      'tickets_bulk_close_confirm': 'هل أنت متأكد من رغبتك في إغلاق جميع التذاكر المفتوحة دفعة واحدة وتحويل حالتها إلى "تم الحل"؟ لا يمكن التراجع عن هذا الإجراء.',
      'tickets_bulk_close_success': 'تم إغلاق كافة التذاكر المفتوحة بنجاح',
      'col_solution': 'طريقة الحل',
      'rows_per_page': 'عدد السجلات بالصفحة:',
      'confirm_delete_ticket_title': 'تأكيد حذف التذكرة',
      'confirm_delete_ticket_msg': 'هل أنت متأكد من رغبتك في حذف هذه التذكرة؟',
      'ticket_delete_success': 'تم حذف التذكرة بنجاح',
      'search_problem_hint': 'ابحث في المشاكل أو أدخل مشكلة جديدة...',
      'problem_types': 'أنواع المشاكل',
      'delete_ticket': 'حذف التذكرة',

      // Attendance & Geofencing Module
      'att_today_status_label': 'حالة دوام اليوم',
      'att_check_in_time': 'وقت الحضور',
      'att_check_out_time': 'وقت الانصراف',
      'att_actual_hours': 'ساعات العمل الفعلية',
      'att_late_minutes': 'دقائق التأخير',
      'att_hours_short': 'س',
      'att_mins_short': 'د',
      'att_days_short': 'أيام',
      'gps_locating_title': 'جاري فحص الموقع الجغرافي...',
      'gps_locating_desc': 'يرجى الانتظار لحين استقبال إشارة الأقمار الصناعية',
      'gps_disabled_title': 'خدمة الـ GPS معطلة',
      'gps_disabled_desc':
          'يرجى تفعيل خدمة تحديد الموقع في الجهاز لتسجيل الدوام',
      'gps_perm_forever_title': 'تم رفض إذن الموقع بشكل دائم',
      'gps_perm_forever_desc': 'يرجى فتح إعدادات التطبيق وتفعيل إذن الموقع',
      'gps_perm_denied_title': 'إذن الموقع مطلوب',
      'gps_perm_denied_desc': 'يرجى منح صلاحية الوصول للموقع الجغرافي',
      'gps_low_accuracy_title': 'دقة الموقع ضعيفة',
      'gps_ready_title': 'إشارة الـ GPS جاهزة',
      'gps_ready_desc': 'الموقع الجغرافي محدد بدقة ممتازة',
      'gps_accuracy_val': 'دقة التحديد: {val} متر',
      'gps_settings_btn': 'فتح الإعدادات',
      'action_check_out': 'تسجيل الانصراف',
      'mock_location_title': 'تحذير أمني: تم اكتشاف تزييف الـ GPS',
      'mock_location_desc': 'يمنع النظام استخدام تطبيقات المواقع الوهمية (Mock Location). تم حظر التسجيل وتوثيق الحادثة بسجل الرقابة.',
      'mock_location_detected_badge': 'موقع وهمي محظور',
      'sync_status_synced': 'متزامن مع السحابة',
      'sync_status_pending': 'معلق للمزامنة',
      'sync_status_pending_count': '{count} سجل بانتظار المزامنة',
      'sync_status_failed': 'فشل المزامنة',
      'sync_status_conflict': 'تعارض بيانات',
      'geofence_inside': 'داخل مقر الشركة',
      'geofence_outside': 'خارج نطاق المقر',
      'geofence_dist': 'المسافة إلى المقر',
      'meters_short': 'م',
      'company_hq_name': 'مقر شركة الفتح الرئيسي',
      'map_recenter_user': 'توسيط موقعي',
      'map_recenter_site': 'توسيط مقر الشركة',
      'att_today_shift_info': 'وردية ومواعيد اليوم',
      'att_shift_default': 'الوردية الصباحية القياسية',
      'att_worked_hours_progress': 'ساعات العمل المسجلة اليوم',
      'att_overtime_earned': 'ساعات عمل إضافية مستحقة',
      'att_week_summary_title': 'ملخص الأسبوع الحالي',
      'att_week_total_hours': 'إجمالي الساعات',
      'att_week_present_days': 'أيام الحضور',
      'att_week_late_minutes': 'دقائق التأخير',
      'att_week_overtime_hours': 'الساعات الإضافية',
      'att_check_in_short': 'حضور',
      'att_check_out_short': 'انصراف',
      'att_late_short': 'تأخير',
      'att_overtime_short': 'إضافي',
      'col_date': 'التاريخ',
      'col_check_in': 'الحضور',
      'col_check_out': 'الانصراف',
      'col_actual_hours': 'الساعات الفعلية',
      'col_late': 'التأخير',
      'col_overtime': 'الإضافي',
      'col_geofence': 'النطاق',
      'col_actions': 'الإجراءات',
      'filter_attendance_title': 'فلترة سجلات الدوام',
      'filter_date_range': 'الفترة الزمنية',
      'filter_select_date_range': 'تحديد تاريخ البدء والانتهاء',
      'filter_status_label': 'حالة الدوام',
      'filter_late_only': 'عرض حالات التأخير فقط',
      'filter_overtime_only': 'عرض ساعات العمل الإضافي فقط',
      'timeline_check_in_title': 'تسجيل الحضور بالـ GPS',
      'timeline_check_out_title': 'تسجيل الانصراف بالـ GPS',
      'timeline_coords': 'الإحداثيات',
      'timeline_accuracy': 'الدقة',
      'timeline_no_events': 'لا توجد أحداث مسجلة لهذا اليوم',
      'att_timeline_header': 'المخطط الزمني وسجل تدقيق الدوام',
      'shift_standard_hours': 'الساعات القياسية',
      'shift_grace_period': 'فترة السماح',
      'shift_overtime_threshold': 'حد الإضافي',
      'active': 'نشط',
      'inactive': 'معطل',
      'currency_sp': 'ل.س',
      'dialog_correction_title': 'طلب تصحيح دوام',
      'target_date': 'تاريخ اليوم المطلوب تصحيحه',
      'corrected_check_in': 'وقت الحضور المقترح',
      'corrected_check_out': 'وقت الانصراف المقترح',
      'correction_reason_label': 'سبب طلب التصحيح',
      'correction_reason_hint': 'اكتب سبب طلب التصحيح بالتفصيل...',
      'correction_reason_required': 'يرجى إدخال سبب طلب التصحيح',
      'submit_request': 'إرسال الطلب',
      'att_no_records_title': 'لا توجد سجلات دوام',
      'error_title': 'حدث خطأ غير متوقع',
      'retry': 'إعادة المحاولة',
      'nav_shifts_management': 'إدارة الورديات',
      'nav_attendance_reports': 'تقارير الدوام والرواتب',
      'nav_attendance_history': 'سجل الحضور',
      'action_request_correction': 'طلب تصحيح دوام',
      'action_view_full_history': 'استعراض السجل الكامل',
      'correction_submitted_success':
          'تم إرسال طلب التصحيح بنجاح، بانتظار اعتماد الإدارة',
      'check_in_view_title': 'تسجيل الحضور والانصراف بالـ GPS',
      'refresh_location': 'تحديث الموقع الجغرافي',
      'att_check_success_msg':
          'تم تسجيل الدوام بنجاح والتحقق من النطاق الجغرافي',
      'history_view_title': 'سجل الحضور والغياب',
      'records_count': 'عدد السجلات',
      'no_attendance_records': 'لا توجد سجلات حضور مطابقة لمعايير البحث',
      'attendance_details_title': 'تفاصيل سجل الدوام',
      'record_not_found': 'لم يتم العثور على سجل الدوام المطلوب',
      'record_id_label': 'رقم السجل',
      'att_metrics_title': 'تفاصيل الوقت وساعات العمل',
      'att_location_details': 'تفاصيل الموقع الجغرافي والنطاق',
      'check_in_location': 'إحداثيات الحضور',
      'gps_accuracy_label': 'دقة تحديد الـ GPS',
      'nav_attendance_correction': 'طلبات تصحيح الدوام',
      'correction_requests_title': 'إدارة طلبات تصحيح الدوام',
      'new_correction_btn': 'طلب تصحيح جديد',
      'my_correction_requests': 'طلباتي',
      'pending_approval_requests': 'طلبات بانتظار الاعتماد',
      'no_correction_requests': 'لا توجد طلبات تصحيح مسجلة',
      'user_id_label': 'الموظف',
      'reason': 'السبب',
      'shifts_management_title': 'إدارة الورديات وفترات الدوام',
      'add_new_shift_btn': 'إضافة وردية جديدة',
      'add_shift_title': 'إضافة وردية دوام جديدة',
      'edit_shift_title': 'تعديل وردية الدوام',
      'shift_name_label': 'اسم الوردية',
      'start_time_label': 'وقت البدء (HH:mm)',
      'end_time_label': 'وقت الانتهاء (HH:mm)',
      'grace_period_label': 'فترة السماح بالدقائق',
      'standard_hours_label': 'الساعات القياسية',
      'delete_shift_title': 'حذف وردية الدوام',
      'delete_shift_confirm': 'هل أنت متأكد من رغبتك في حذف الوردية',
      'no_shifts_found': 'لا توجد ورديات مسجلة',
      'attendance_reports_title': 'تقارير الحضور والرواتب',
      'report_exported_success': 'تم تصدير التقرير بنجاح إلى',
      'report_export_failed': 'فشل تصدير التقرير، يرجى المحاولة لاحقاً',
      'select_report_period': 'تحديد فترة التقرير',
      'period_daily': 'اليومي',
      'period_weekly': 'الأسبوعي',
      'period_monthly': 'الشهري',
      'kpi_present_days': 'أيام الحضور',
      'kpi_total_hours': 'مجموع الساعات',
      'kpi_overtime_hours': 'الساعات الإضافية',
      'kpi_late_minutes': 'دقائق التأخير',
      'export_report_title': 'تصدير التقرير',
      'no_report_data': 'لا توجد بيانات دوام خلال الفترة المحددة',
      'report_details_table_title': 'جدول تفاصيل دوام الموظفين',
      'approve': 'اعتماد',
      'reject': 'رفض',
    },
    'en': {
      // General & Actions
      'app_name': 'Al-Fateh ISP Management',
      'app_subtitle': 'Integrated Internet Services Management System',
      'welcome_admin': 'Welcome to Al-Fateh Control Center',
      'status_connected': 'Server Connected',
      'status_connected_short': 'Connected',
      'theme_system': 'System Theme (Auto)',
      'theme_dark': 'Dark Mode',
      'theme_light': 'Light Mode',
      'lang_system': 'Device Language (Auto)',
      'lang_ar': 'Arabic',
      'lang_en': 'English',
      'lang_switch': 'العربية',
      'confirm': 'Confirm',
      'cancel': 'Cancel',
      'close': 'Close',
      'save': 'Save',
      'delete': 'Delete',
      'edit': 'Edit',
      'search': 'Search',
      'filter': 'Filter',
      'refresh': 'Refresh',
      'back': 'Back',
      'logout': 'Sign Out',
      'or': 'Or',

      // Splash Screen
      'splash_loading': 'Initializing Al-Fateh System...',
      'splash_version': 'Version 1.0.0 Unified',
      'splash_step_resources': 'Loading resources and typography...',
      'splash_step_network': 'Verifying server connection settings...',
      'splash_step_system': 'Configuring Al-Fateh Management System...',
      'splash_step_completed': 'Initialization completed successfully',

      // Services Hub
      'services_title': 'ISP Administrative Services',
      'service_support': 'Technical Support & Follow-up',
      'service_support_desc': 'Track subscriber calls, resolve tickets, and real-time Google Sheets sync',
      'service_support_loading': 'Preparing tickets and follow-up table...',
      'service_subscribers': 'Subscribers & Lines Management',
      'service_subscribers_desc':
          'Account records, packages, and subscription renewal',
      'service_network': 'Network & DSLAM Monitoring',
      'service_network_desc':
          'Monitor service stability, line quality, and server performance',
      'service_billing': 'Billing & Financial Accounts',
      'service_billing_desc':
          'Monthly collections, receivables, and ISP financial reports',
      'coming_soon': 'Under Development',
      'active_now': 'Active & Available',
      'enter_service': 'Open Service',

      // Technical Support & Tickets
      'status_resolved': 'Resolved',
      'status_in_progress': 'In Progress',
      'status_unresolved': 'Unresolved',
      'ticket_new': 'New Ticket',
      'ticket_number': 'Ticket #',
      'subscriber_name': 'Subscriber Name',
      'landline_number': 'Landline Number',
      'problem_type': 'Problem Type',
      'solution_method': 'Resolution Method',
      'description': 'Description',
      'employee': 'Employee',
      'date': 'Date',
      'time': 'Time',
      'actions': 'Actions',
      'no_data': 'No data available at the moment',

      // Form Validation
      'val_required': 'This field is required',
      'val_landline_empty': 'Please enter phone number',
      'val_landline_digits': 'Phone number must contain digits only',
      'val_landline_length': 'Phone number must be exactly 10 digits',
      'val_subscriber_empty': 'Please enter subscriber name',
      'val_subscriber_length': 'Subscriber name is too short (min 3 chars)',
      'val_mobile_empty': 'Please enter mobile phone number',
      'val_mobile_invalid': 'Mobile number must be 10 digits (e.g. 09xxxxxxxx)',
      'val_username_empty': 'Please enter username',
      'val_password_empty': 'Please enter password',
      'val_password_short': 'Password too short (min 4 characters)',

      // Authentication & Login
      'login_title': 'System Authentication',
      'login_subtitle':
          'Enter your credentials to access the management portal',
      'username': 'Username',
      'username_hint': 'e.g. admin or hashem',
      'password': 'Password',
      'password_hint': '••••••••',
      'remember_me': 'Remember me on this device',
      'remember_me_tooltip':
          'Save session for quick offline access and auto-fill',
      'sign_in': 'Sign In',
      'signing_in': 'Authenticating credentials...',
      'login_success': 'Successfully authenticated',
      'offline_mode_banner': 'Logged in offline mode (cached local session)',
      'forgot_password': 'Forgot password?',
      'forgot_password_desc':
          'Please contact Al-Fateh Administration to reset credentials',
      'show_password': 'Show password',
      'hide_password': 'Hide password',
      'need_help': 'Need assistance?',
      'contact_admin': 'Contact System Administration',
      'security_badge': 'Secure 256-bit Encrypted Connection',
      'preview_skeleton': 'Preview Skeleton Loading',
      'login_brand_desc': 'Unified control portal for ISP operations, subscriber follow-ups, and intelligent attendance.',
      'feature_tickets_title': 'Real-time Support Tickets Management',
      'feature_tickets_desc':
          'Direct synchronization with Google Sheets & subscriber statuses',
      'feature_geofence_title': 'Smart Attendance with Geofencing',
      'feature_geofence_desc':
          'Accurate check-in/out within HQ premises and branch locations',
      'feature_rbac_title': 'Advanced Security & RBAC Permissions',
      'feature_rbac_desc':
          'Fine-grained role permissions with immutable audit trail logs',
      'whatsapp_contact': 'Contact Support on WhatsApp',
      'whatsapp_launch_error':
          'Could not launch WhatsApp, please try again later',
      'login_error_empty_fields': 'Please enter username and password',
      'login_error_invalid_password': 'Incorrect password',
      'login_error_user_not_found': 'Username not found',
      'login_error_account_disabled':
          'This account has been disabled, please contact Al-Fateh admin',
      'login_error_network':
          'Unable to connect to server, please check your network connection',
      'login_error_generic':
          'Login failed, please check your credentials and try again',

      // Navigation & Sections
      'nav_home': 'Home',
      'nav_tickets': 'Technical Tickets',
      'nav_attendance': 'Attendance',
      'nav_employees': 'Staff & Roles',
      'nav_settings': 'Settings & Account',

      // Confirm Dialog
      'confirm_logout_title': 'Confirm Sign Out',
      'confirm_logout_msg':
          'Are you sure you want to sign out of Al-Fateh System?',
      'confirm_logout_message':
          'Are you sure you want to sign out of Al-Fateh System?',
      'confirm_logout_button': 'Sign Out',
      'toggle_sidebar': 'Toggle Sidebar',

      // Dashboard & Statistics
      'stat_total_tickets': 'Total Tickets',
      'stat_in_progress': 'In Progress',
      'stat_resolved_today': 'Resolved Today',
      'stat_attendance_status': 'Attendance Today',
      'stat_present': 'Present at Work',
      'stat_not_checked_in': 'Not Checked In',
      'stat_active_users': 'Active Staff',
      'stat_quick_actions': 'Quick Actions',
      'stat_recent_tickets': 'Recent Support Tickets',
      'stat_view_all': 'View All',
      'stat_refresh_data': 'Refresh Data',
      'stat_offline_indicator': 'Offline Local Cache Mode',
      'action_new_ticket': 'New Ticket',
      'action_check_in': 'Clock In / Out',
      'action_manage_users': 'Manage Users',
      'action_payroll_audit': 'Payroll Audit',
      'action_settings': 'Account Settings',

      // Modules Placeholders
      'tickets_view_title': 'Technical Support & Tickets Management',
      'tickets_view_desc': 'Manage subscriber calls, log hardware issues, and real-time Google Sheets tracking',
      'attendance_view_title': 'Smart GPS Attendance & Geofenced Clock',
      'attendance_view_desc': 'Check-in with GPS verification within company geofence radius and shifts management',
      'employees_view_title': 'Staff, Accounts & RBAC Permissions',
      'employees_view_desc': 'Manage staff roster, access permissions matrix, and immutable audit logs',
      'settings_view_title': 'Application & Profile Settings',
      'settings_view_desc': 'Manage theme preferences, language, security, and active session details',

      // User Roles
      'role_admin': 'System Administrator',
      'role_gm': 'General Manager',
      'role_finance': 'Finance & Accounting',
      'role_support_manager': 'Support Manager',
      'role_sales_manager': 'Sales Manager',
      'role_support': 'Technical Support',
      'role_sales': 'Sales Representative',

      // Errors
      'error_network_connection':
          'No internet connection, please check network',
      'error_network_timeout': 'Server request timed out, please retry',
      'error_server_internal': 'Unexpected internal server error',
      'error_unauthorized': 'Unauthorized session, please log in again',
      'error_forbidden': 'You do not have permission to perform this action',
      'error_not_found': 'The requested record was not found',
      'error_validation_failed': 'Form input validation failed',
      'error_cache_failure': 'Failed to access local encrypted storage',
      'error_unknown': 'An unexpected error occurred',
      'auth_session_expired':
          'Local session expired, please connect to internet and log in again',

      // Tickets Module
      'search_tickets_hint': 'Search phone, subscriber, problem type...',
      'switch_to_cards': 'Switch to Cards view',
      'switch_to_table': 'Switch to Table view',
      'add_ticket_btn': 'Add Ticket',
      'col_ticket_id': 'Ticket ID',
      'col_subscriber': 'Subscriber',
      'col_landline': 'Landline',
      'col_problem': 'Problem Type',
      'col_status': 'Status',
      'col_employee': 'Assignee',
      'col_date_time': 'Date & Time',
      'view_details': 'View Details',
      'edit_ticket': 'Edit Ticket',
      'all': 'All',
      'showing': 'Showing',
      'clear_filters': 'Clear Filters',
      'selected_items': 'Selected items',
      'clear_selection': 'Clear Selection',
      'page': 'Page',
      'unassigned': 'Unassigned',
      'badge_complaint': 'Complaint',
      'pending_sync': 'Pending Cloud Sync',
      'status_syncing': 'Syncing...',
      'status_offline_cache': 'Offline Cache',
      'sync_now_tooltip': 'Sync now',
      'no_tickets_found_title': 'No Matching Tickets Found',
      'no_tickets_found_desc':
          'No tickets match your active search or filter criteria',
      'dialog_add_ticket_title': 'Create Support Ticket',
      'dialog_add_ticket_desc':
          'Enter subscriber details and describe the technical inquiry',
      'subscriber_name_label': 'Subscriber Name',
      'subscriber_name_hint': 'Enter subscriber full name',
      'val_subscriber_required': 'Subscriber name is required',
      'landline_label': 'Landline Phone',
      'val_landline_required': 'Landline phone is required',
      'mobile_label': 'Mobile Number',
      'problem_type_label': 'Problem Type',
      'add_new_problem_type': 'Add New Problem',
      'new_problem_name_hint': 'Enter new problem name...',
      'select_problem_required': 'Please select or add a problem type',
      'assigned_to_label': 'Assigned Employee',
      'priority_label': 'Priority Level',
      'is_complaint_ticket': 'Complaint Follow-up Ticket',
      'is_complaint_ticket_desc':
          'Flag as complaint for priority escalation and tracking',
      'description_label': 'Call Description & Notes',
      'description_hint': 'Enter problem details and notes...',
      'save_ticket_btn': 'Save Ticket',
      'tab_ticket_details': 'Ticket Details & Resolution',
      'tab_audit_trail': 'Audit Trail & History',
      'update_status_label': 'Quick Status Update',
      'solution_method_label': 'Resolution Method',
      'solution_method_hint': 'Describe actions taken to resolve the issue...',
      'audit_notes_label': 'Audit Notes & Reason',
      'audit_notes_hint': 'Document reason for modification...',
      'save_changes': 'Save Changes',
      'no_audit_history': 'No audit history recorded yet for this ticket',
      'ticket_add_success': 'Ticket created successfully',
      'ticket_update_success': 'Ticket updated successfully',
      'problem_add_success': 'New problem type added successfully',
      'sync_success': 'All pending operations synchronized successfully',
      'close_all_tickets_btn': 'Close All Tickets',
      'tickets_bulk_close_title': 'Confirm Closing All Open Tickets',
      'tickets_bulk_close_confirm': 'Are you sure you want to close all open tickets at once and mark them as resolved? This action cannot be undone.',
      'tickets_bulk_close_success': 'All open tickets closed successfully',
      'col_solution': 'Resolution Method',
      'rows_per_page': 'Rows per page:',
      'confirm_delete_ticket_title': 'Confirm Delete Ticket',
      'confirm_delete_ticket_msg':
          'Are you sure you want to delete this ticket?',
      'ticket_delete_success': 'Ticket deleted successfully',
      'search_problem_hint': 'Search problems or add a new one...',
      'problem_types': 'Problem Types',
      'delete_ticket': 'Delete Ticket',

      // Attendance & Geofencing Module
      'att_today_status_label': 'Today Status',
      'att_check_in_time': 'Check-In Time',
      'att_check_out_time': 'Check-Out Time',
      'att_actual_hours': 'Actual Hours',
      'att_late_minutes': 'Late Minutes',
      'att_hours_short': 'hrs',
      'att_mins_short': 'mins',
      'att_days_short': 'days',
      'gps_locating_title': 'Acquiring GPS location...',
      'gps_locating_desc': 'Please wait while acquiring satellite fix',
      'gps_disabled_title': 'GPS Service Disabled',
      'gps_disabled_desc': 'Please enable location services to proceed',
      'gps_perm_forever_title': 'Location Permission Permanently Denied',
      'gps_perm_forever_desc':
          'Please open app settings and grant location access',
      'gps_perm_denied_title': 'Location Permission Required',
      'gps_perm_denied_desc': 'Please grant location access',
      'gps_low_accuracy_title': 'Low GPS Accuracy',
      'gps_ready_title': 'GPS Signal Ready',
      'gps_ready_desc': 'Location is accurately determined',
      'gps_accuracy_val': 'Accuracy: {val} meters',
      'gps_settings_btn': 'Settings',
      'action_check_out': 'Check Out',
      'mock_location_title': 'Security Alert: Mock GPS Detected',
      'mock_location_desc': 'Mock GPS applications are strictly forbidden. Action is blocked and logged.',
      'mock_location_detected_badge': 'Mock Location Detected',
      'sync_status_synced': 'Synced',
      'sync_status_pending': 'Pending Sync',
      'sync_status_pending_count': '{count} pending sync',
      'sync_status_failed': 'Sync Failed',
      'sync_status_conflict': 'Data Conflict',
      'geofence_inside': 'Inside HQ',
      'geofence_outside': 'Outside HQ',
      'geofence_dist': 'Distance to HQ',
      'meters_short': 'm',
      'company_hq_name': 'Al-Fateh HQ',
      'map_recenter_user': 'Center my location',
      'map_recenter_site': 'Center HQ',
      'att_today_shift_info': 'Assigned Shift for Today',
      'att_shift_default': 'Standard Morning Shift',
      'att_worked_hours_progress': 'Worked Hours Progress',
      'att_overtime_earned': 'Earned Overtime',
      'att_week_summary_title': 'Current Week Summary',
      'att_week_total_hours': 'Total Hours',
      'att_week_present_days': 'Days Present',
      'att_week_late_minutes': 'Late Minutes',
      'att_week_overtime_hours': 'Overtime Hours',
      'att_check_in_short': 'In',
      'att_check_out_short': 'Out',
      'att_late_short': 'Late',
      'att_overtime_short': 'OT',
      'col_date': 'Date',
      'col_check_in': 'Check In',
      'col_check_out': 'Check Out',
      'col_actual_hours': 'Hours',
      'col_late': 'Late',
      'col_overtime': 'Overtime',
      'col_geofence': 'Geofence',
      'col_actions': 'Actions',
      'filter_attendance_title': 'Filter Attendance Records',
      'filter_date_range': 'Date Range',
      'filter_select_date_range': 'Select start and end date',
      'filter_status_label': 'Attendance Status',
      'filter_late_only': 'Show late records only',
      'filter_overtime_only': 'Show overtime records only',
      'timeline_check_in_title': 'Check-in via GPS',
      'timeline_check_out_title': 'Check-out via GPS',
      'timeline_coords': 'Coordinates',
      'timeline_accuracy': 'Accuracy',
      'timeline_no_events': 'No events recorded for today',
      'att_timeline_header': 'Timeline & Audit Log',
      'shift_standard_hours': 'Standard Hours',
      'shift_grace_period': 'Grace Period',
      'shift_overtime_threshold': 'Overtime Threshold',
      'active': 'Active',
      'inactive': 'Inactive',
      'currency_sp': 'SYP',
      'dialog_correction_title': 'Request Attendance Correction',
      'target_date': 'Target Date',
      'corrected_check_in': 'Corrected Check In',
      'corrected_check_out': 'Corrected Check Out',
      'correction_reason_label': 'Correction Reason',
      'correction_reason_hint': 'Explain the reason in detail...',
      'correction_reason_required': 'Correction reason is required',
      'submit_request': 'Submit Request',
      'att_no_records_title': 'No Attendance Records',
      'error_title': 'An error occurred',
      'retry': 'Retry',
      'nav_shifts_management': 'Shift Management',
      'nav_attendance_reports': 'Attendance Reports',
      'nav_attendance_history': 'Attendance History',
      'action_request_correction': 'Request Correction',
      'action_view_full_history': 'View Full History',
      'correction_submitted_success':
          'Correction request submitted successfully, awaiting approval',
      'check_in_view_title': 'GPS Attendance Check-in',
      'refresh_location': 'Refresh Location',
      'att_check_success_msg':
          'Attendance recorded and geofence verified successfully',
      'history_view_title': 'Attendance History',
      'records_count': 'Records Count',
      'no_attendance_records': 'No attendance records match your criteria',
      'attendance_details_title': 'Attendance Record Details',
      'record_not_found': 'Record not found',
      'record_id_label': 'Record ID',
      'att_metrics_title': 'Time & Hours Metrics',
      'att_location_details': 'Location & Geofence Details',
      'check_in_location': 'Check-in Coordinates',
      'gps_accuracy_label': 'GPS Accuracy',
      'nav_attendance_correction': 'Correction Requests',
      'correction_requests_title': 'Attendance Correction Requests',
      'new_correction_btn': 'New Request',
      'my_correction_requests': 'My Requests',
      'pending_approval_requests': 'Pending Approvals',
      'no_correction_requests': 'No correction requests found',
      'user_id_label': 'Employee',
      'reason': 'Reason',
      'shifts_management_title': 'Shift Management',
      'add_new_shift_btn': 'Add New Shift',
      'add_shift_title': 'Add New Shift',
      'edit_shift_title': 'Edit Shift',
      'shift_name_label': 'Shift Name',
      'start_time_label': 'Start Time (HH:mm)',
      'end_time_label': 'End Time (HH:mm)',
      'grace_period_label': 'Grace Period (mins)',
      'standard_hours_label': 'Standard Hours',
      'delete_shift_title': 'Delete Shift',
      'delete_shift_confirm': 'Are you sure you want to delete shift',
      'no_shifts_found': 'No shifts found',
      'attendance_reports_title': 'Attendance & Payroll Reports',
      'report_exported_success': 'Report exported successfully to',
      'report_export_failed': 'Failed to export report, please try again',
      'select_report_period': 'Select Report Period',
      'period_daily': 'Daily',
      'period_weekly': 'Weekly',
      'period_monthly': 'Monthly',
      'kpi_present_days': 'Days Present',
      'kpi_total_hours': 'Total Hours',
      'kpi_overtime_hours': 'Overtime Hours',
      'kpi_late_minutes': 'Late Minutes',
      'export_report_title': 'Export Report',
      'no_report_data': 'No attendance data for selected period',
      'report_details_table_title': 'Employee Attendance Details Table',
      'approve': 'Approve',
      'reject': 'Reject',
    },
  };

  String translate(String key) {
    return _localizedValues[locale.languageCode]?[key] ??
        _localizedValues['ar']?[key] ??
        key;
  }
}

class _AppLocalizationsDelegate
    extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => ['ar', 'en'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async {
    return AppLocalizations(locale);
  }

  @override
  bool shouldReload(_AppLocalizationsDelegate old) => false;
}

extension LocalizationExtension on BuildContext {
  AppLocalizations get loc => AppLocalizations.of(this);
  String tr(String key) => loc.translate(key);
  String trServer(dynamic messageOrError) =>
      BackendMessageTranslator.translate(this, messageOrError);
}
